### ISSUE TITLE
Shutdown Script

### ISSUE THREAD

**Issue by zeroark** [Daztek/EventSystem#2]
Hello!
Not sure if an error or just outdated documentation but I noticed this error today when I was updating the Event System on my module to the latest version

![image](https://user-images.githubusercontent.com/588800/81902704-3379d480-9586-11ea-917a-95b438703f62.png)

Documentation says to use `es_obj_e_2018`, but the script and that warning advise to use `es_obj_e_3018`. 

Which is the correct one in the end?

**Comment by Daztek** [comment]
Weird, my readme says 3018 ;D

(Fixed, thank you)
